compile-base:build:
  stage: build
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    IMG_TAG: compile
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --squash --cache-from $CI_REGISTRY_IMAGE:$IMG_TAG -t $CI_REGISTRY_IMAGE:$IMG_TAG -f build-conf/compile/base.Dockerfile build-src
    - docker push "$CI_REGISTRY_IMAGE:$IMG_TAG"
  rules:
    - changes:
        - build-conf/compile/base.Dockerfile

depends:
  stage: build
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    OSX_SDK: 10:11
  parallel:
    matrix:
      - TARGET: x86_64-apple-darwin11
        PACKAGE: imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev python3-setuptools-git
      - TARGET: x86_64-unknown-freebsd
        PACKAGE: clang-8 libdbus-1-dev libharfbuzz-dev
      - TARGET: x86_64-unknown-linux-gnu
        PACKAGE: libdbus-1-dev libharfbuzz-dev
      - TARGET: i686-pc-linux-gnu
        PACKAGE: gcc-multilib-i686-linux-gnu
      - TARGET: x86_64-w64-mingw32
        PACKAGE: g++-mingw-w64-x86-64
      - TARGET: i686-w64-mingw32
        PACKAGE: g++-mingw-w64-i686
      - TARGET: arm-linux-gnueabihf
        PACKAGE: g++-arm-linux-gnueabihf
      - TARGET: aarch64-linux-gnu
        PACKAGE: g++-aarch64-linux-gnu
      - TARGET: riscv64-linux-gnu
        PACKAGE: g++-riscv64-linux-gnu
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --squash --build-arg TARGET=$TARGET --build-arg PACKAGE=$PACKAGE --cache-from $CI_REGISTRY_IMAGE:depends-$TARGET -t $CI_REGISTRY_IMAGE:depends-$TARGET -f build-conf/compile/depends.Dockerfile build-src
    - docker push "$CI_REGISTRY_IMAGE:depends-$TARGET"
  rules:
    - changes:
        - build-conf/compile/depends.Dockerfile


#compile-win64:deploy:
#  stage: deploy
#  needs: ["compile-win64:build"]
#  image: docker
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#    IMG_TAG: compile-win64
#  services:
#    - name: docker:dind
#      command: [ "--experimental" ]
#  before_script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
#  script:
#    - docker pull $CI_REGISTRY_IMAGE:$IMG_TAG
#    - docker tag $CI_REGISTRY_IMAGE:$IMG_TAG $DOCKER_REGISTRY_IMAGE:$IMG_TAG
#    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_IMAGE:$IMG_TAG
#  environment:
#    name: $IMG_TAG
#  rules:
#    - if: $CI_COMMIT_BRANCH == 'main'
#      changes:
#        - build-conf/compile/win64.Dockerfile
