base-ubuntu-build:
  stage: build
  image: docker
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  allow_failure: true
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --squash --cache-from $CI_REGISTRY_IMAGE:base-ubuntu -t $CI_REGISTRY_IMAGE:base-ubuntu -f build-conf/base/ubuntu/20-04.Dockerfile build-src
    - docker push "$CI_REGISTRY_IMAGE:base-ubuntu"
  rules:
    - changes:
        - build-conf/base/ubuntu/20-04.Dockerfile
        - build-conf/base/.gitlab-ci.yml

