wallet:
  stage: build
  image: jdrouet/docker-with-buildx:stable
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  parallel:
    matrix:
      - BUILD: windows
      - BUILD: linux
      - BUILD: android
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build --platform linux/amd64 --build-arg BUILD=$BUILD --cache-from $CI_REGISTRY_IMAGE:wallet-$BUILD -t $CI_REGISTRY_IMAGE:wallet-$BUILD -f build-conf/wallet/$BUILD.Dockerfile build-src
    - docker push "$CI_REGISTRY_IMAGE:wallet-$BUILD"

wallet:deploy:
  stage: deploy
  needs: ["wallet"]
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  parallel:
    matrix:
      - TARGET: wallet-windows
      - TARGET: wallet-linux
      - TARGET: wallet-android
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$TARGET
    - docker tag $CI_REGISTRY_IMAGE:$TARGET $DOCKER_REGISTRY/lthn/build:$TARGET
    - docker push $DOCKER_REGISTRY/lthn/build:$TARGET
  environment:
    name: $IMG_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'


sources:
  stage: build
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
  parallel:
    matrix:
      - BUILD: osx
      - BUILD: linux
      - BUILD: win
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - sleep $(shuf -i1-180 -n1);
  script:
    - docker build --squash --build-arg BUILD=$BUILD -t $CI_REGISTRY_IMAGE:sources-$BUILD -f build-conf/compile/sources.Dockerfile build-src
    - docker push "$CI_REGISTRY_IMAGE:sources-$BUILD"
  rules:
    - changes:
        - build-conf/compile/sources.Dockerfile


sources:deploy:
  stage: deploy
  needs: ["sources"]
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  parallel:
    matrix:
      - TARGET: sources-osx
      - TARGET: sources-linux
      - TARGET: sources-win
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$TARGET
    - docker tag $CI_REGISTRY_IMAGE:$TARGET $DOCKER_REGISTRY/lthn/build:$TARGET
    - docker push $DOCKER_REGISTRY/lthn/build:$TARGET
  environment:
    name: $IMG_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      changes:
          - build-conf/compile/sources.Dockerfile