wallet.linux.build:
  stage: build
  image: docker
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  allow_failure: true
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:wallet-linux -t $CI_REGISTRY_IMAGE:wallet-linux -f build-conf/wallet/linux.Dockerfile src
    - docker push "$CI_REGISTRY_IMAGE:wallet-linux"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: manual
    - changes:
        - build-conf/wallet/linux.Dockerfile
      when: manual

wallet.windows.build:
  stage: build
  image: docker
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  allow_failure: true
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:wallet-windows -t $CI_REGISTRY_IMAGE:wallet-windows -f build-conf/wallet/windows.Dockerfile src
    - docker push "$CI_REGISTRY_IMAGE:wallet-windows"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: manual
      changes:
        - build-conf/wallet/windows.Dockerfile
    - if: $CI_COMMIT_BRANCH == 'master'
      when: manual

wallet.android.build:
  stage: build
  image: docker
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  allow_failure: true
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:wallet-android -t $CI_REGISTRY_IMAGE:wallet-android -f build-conf/wallet/android.Dockerfile src
    - docker push "$CI_REGISTRY_IMAGE:wallet-android"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: manual
    - changes:
        - build-conf/wallet/android.Dockerfile
      when: manual
